/**
 * Creep Data Specification from Google Docs:
 * - Melee and Ranged creeps (Levels 1 to 5)
 * - Wave formation cycles: 1R4M -> 2R3M -> 2R5M -> 4R5M
 * - First wave at 60s, then every 60s
 * - Neutral creep camp formations (120s spawn, then every 60s)
 */

export const CREEP_STATS = {
  1: {
    melee: {
      type: 'MELEE',
      level: 1,
      hp: 100,
      vision: 5,
      damage: 20,
      period: 4.0,
      critDamage: 40,
      range: 1,
      penetration: 10,
      hit: 50,
      speed: 6,
      armor: 0,
      agility: 0,
    },
    ranged: {
      type: 'RANGED',
      level: 1,
      hp: 80,
      vision: 5,
      damage: 25,
      period: 4.0,
      critDamage: 50,
      range: 5,
      penetration: 5,
      hit: 15,
      speed: 6,
      armor: 0,
      agility: 0,
    },
  },
  2: {
    melee: {
      type: 'MELEE',
      level: 2,
      hp: 200,
      vision: 7,
      damage: 35,
      period: 4.0,
      critDamage: 40,
      range: 1,
      penetration: 10,
      hit: 50,
      speed: 6,
      armor: 1,
      agility: 1,
    },
    ranged: {
      type: 'RANGED',
      level: 2,
      hp: 160,
      vision: 8,
      damage: 45,
      period: 4.0,
      critDamage: 50,
      range: 7,
      penetration: 5,
      hit: 20,
      speed: 6,
      armor: 1,
      agility: 1,
    },
  },
  3: {
    melee: {
      type: 'MELEE',
      level: 3,
      hp: 300,
      vision: 10,
      damage: 50,
      period: 4.0,
      critDamage: 100,
      range: 1,
      penetration: 10,
      hit: 50,
      speed: 6,
      armor: 1,
      agility: 1,
    },
    ranged: {
      type: 'RANGED',
      level: 3,
      hp: 240,
      vision: 12,
      damage: 75,
      period: 4.0,
      critDamage: 150,
      range: 10,
      penetration: 5,
      hit: 25,
      speed: 6,
      armor: 1,
      agility: 1,
    },
  },
  4: {
    melee: {
      type: 'MELEE',
      level: 4,
      hp: 400,
      vision: 10,
      damage: 65,
      period: 4.0,
      critDamage: 130,
      range: 2,
      penetration: 15,
      hit: 50,
      speed: 8,
      armor: 1,
      agility: 1,
    },
    ranged: {
      type: 'RANGED',
      level: 4,
      hp: 320,
      vision: 12,
      damage: 80,
      period: 4.0,
      critDamage: 160,
      range: 12,
      penetration: 5,
      hit: 30,
      speed: 8,
      armor: 1,
      agility: 1,
    },
  },
  5: {
    melee: {
      type: 'MELEE',
      level: 5,
      hp: 500,
      vision: 12,
      damage: 80,
      period: 4.0,
      critDamage: 160,
      range: 2,
      penetration: 15,
      hit: 50,
      speed: 10,
      armor: 1,
      agility: 1,
    },
    ranged: {
      type: 'RANGED',
      level: 5,
      hp: 400,
      vision: 15,
      damage: 100,
      period: 4.0,
      critDamage: 200,
      range: 15,
      penetration: 5,
      hit: 35,
      speed: 10,
      armor: 1,
      agility: 1,
    },
  },
};

export const LANE_WAVE_FORMATIONS = [
  { ranged: 1, melee: 4 }, // 1R 4M
  { ranged: 2, melee: 3 }, // 2R 3M
  { ranged: 2, melee: 5 }, // 2R 5M
  { ranged: 4, melee: 5 }, // 4R 5M
];

export const NEUTRAL_CAMP_FORMATIONS = [
  { description: '2 M (5 ур.)', units: [{ type: 'melee', level: 5, count: 2 }] },
  { description: '2 R (4 ур.) 1 M (5 ур.)', units: [{ type: 'ranged', level: 4, count: 2 }, { type: 'melee', level: 5, count: 1 }] },
  { description: '2 R (3 ур.) 5 M (1 ур.)', units: [{ type: 'ranged', level: 3, count: 2 }, { type: 'melee', level: 1, count: 5 }] },
  { description: '1 R (5 ур.) 4 M (2 ур.)', units: [{ type: 'ranged', level: 5, count: 1 }, { type: 'melee', level: 2, count: 4 }] },
];
