/**
 * Hero Roster Data according to Google Docs Specification & Canonical Lore:
 * Fully detailed for:
 * 1. Albert Wesker
 * 2. Axe
 * 3. Katarina
 * 4. Alexander Anderson
 * 5. Gojo Satoru
 * 6. Ryomen Sukuna
 * 7. Pudge
 * 8. Invoker
 * 9. Rubick
 * 10. Shadow Fiend
 * 11. m0NESY
 * 12. Minos Prime
 */

export const HEROES_ROSTER = [
  {
    id: 'wesker',
    name: 'Albert Wesker',
    title: 'S.T.A.R.S. Captain / Уроборос',
    heroClass: 'AGILITY',
    faction: 'dire',
    themeColor: '#1e293b',
    accentColor: '#ef4444',
    avatarSymbol: 'AW',
    avatarUrl: '/avatars/wesker_avatar.png',
    stats: {
      level: 1,
      hp: 100,
      maxHp: 100,
      hpRegen: 5,
      mana: 150,
      maxMana: 150,
      manaRegen: 10,
      vision: 10,
      speed: 6,
      armor: 1,
      agility: 5,
      // Active weapon mode: 'ranged' or 'melee'
      weaponMode: 'ranged',
      melee: {
        damage: 5,
        period: 4.0,
        critDamage: 20,
        range: 1,
        penetration: 1,
        hit: 50,
      },
      ranged: {
        damage: 40,
        period: 4.0,
        critDamage: 90,
        range: 5,
        penetration: 15,
        hit: 20,
      },
    },
    skills: [
      {
        id: 'stars-agent',
        name: 'S.T.A.R.S. Agent',
        type: 'ACTIVE',
        timeCost: 2.0,
        manaCost: 0,
        cooldown: 0,
        desc: 'Переключение между пистолетом (дальний бой) и кулаками (ближний бой).',
      },
      {
        id: 'ouroboros',
        name: 'Ouroboros',
        type: 'PASSIVE',
        timeCost: 0,
        manaCost: 0,
        desc: 'Вирус повышает регенерацию (+5), броню (+5), урон с руки (+5) и пробитие (+3).',
      },
      {
        id: 'wesker-speed',
        name: 'Speed',
        type: 'PASSIVE',
        timeCost: 0,
        manaCost: 0,
        desc: 'Вирус ускоряет Вескера: +4 к скорости перемещения, +5 к ловкости.',
      },
      {
        id: 'mastermind',
        name: 'Mastermind',
        type: 'ULTIMATE',
        timeCost: 0,
        manaCost: 150,
        duration: 8.0,
        cooldown: 100.0,
        desc: 'Ульта: уклонение от всех атак и направленных скиллов, скорость x2, скорость действий x2 на 8 секунд.',
      },
    ],
  },
  {
    id: 'axe',
    name: 'Axe',
    title: 'Mogul Khan / Варвар',
    heroClass: 'STRENGTH',
    faction: 'radiant',
    themeColor: '#7f1d1d',
    accentColor: '#f97316',
    avatarSymbol: 'AX',
    avatarUrl: '/avatars/axe_avatar.png',
    stats: {
      level: 1,
      hp: 150,
      maxHp: 150,
      hpRegen: 10,
      mana: 100,
      maxMana: 100,
      manaRegen: 10,
      vision: 8,
      speed: 6,
      armor: 5,
      agility: 1,
      damage: 50,
      period: 4.0,
      critDamage: 100,
      range: 1,
      penetration: 15,
      hit: 50,
    },
    skills: [
      {
        id: 'berserkers-call',
        name: "Berserker's Call",
        type: 'ACTIVE',
        timeCost: 2.0,
        manaCost: 25,
        radius: 2,
        duration: 4.0,
        cooldown: 20.0,
        desc: 'Провоцирует врагов в радиусе 2 клеток атаковать Акса.',
      },
      {
        id: 'battle-hunger',
        name: 'Battle Hunger',
        type: 'ACTIVE',
        timeCost: 2.0,
        manaCost: 25,
        range: 6,
        duration: 2.0,
        cooldown: 16.0,
        desc: 'Периодический урон 10/сек и замедление врага на 10%.',
      },
      {
        id: 'counter-helix',
        name: 'Counter Helix',
        type: 'PASSIVE',
        timeCost: 0,
        manaCost: 0,
        radius: 1,
        damage: 50,
        desc: 'Кружится с топором при получении ударов: 50 чистого урона вокруг.',
      },
      {
        id: 'culling-blade',
        name: 'Culling Blade',
        type: 'ULTIMATE',
        timeCost: 1.0,
        manaCost: 75,
        range: 2,
        damage: 100,
        cooldown: 80.0,
        desc: 'Рубящий удар топором: 100 урона. При добивании сбрасывает кулдаун и даёт +10% урона.',
      },
    ],
  },
  {
    id: 'katarina',
    name: 'Катарина',
    title: 'Гибельный Клинок (Noxian Assassin)',
    heroClass: 'AGILITY',
    faction: 'dire',
    themeColor: '#881337',
    accentColor: '#f43f5e',
    avatarSymbol: 'KT',
    avatarUrl: '/avatars/katarina_avatar.svg',
    stats: {
      level: 1,
      hp: 100,
      maxHp: 100,
      hpRegen: 5,
      mana: 100,
      maxMana: 100,
      manaRegen: 10,
      vision: 10,
      speed: 6,
      armor: 2,
      agility: 5,
      damage: 40,
      period: 4.0,
      critDamage: 80,
      range: 1,
      penetration: 10,
      hit: 5,
    },
    skills: [
      {
        id: 'voracity',
        name: 'Ненасытность & Кинжалы',
        type: 'PASSIVE',
        timeCost: 0,
        manaCost: 0,
        desc: 'При подборе кинжала круговая атака на 31 урона. Убийство врага снижает КД способностей на 16 сек.',
      },
      {
        id: 'bouncing-blade',
        name: 'Танцующий клинок',
        type: 'ACTIVE',
        timeCost: 2.0,
        manaCost: 30,
        range: 4,
        damage: 40,
        cooldown: 16.0,
        desc: 'Мечет кинжал, отскакивающий по 2 целям (40 урона), кинжал падает на землю.',
      },
      {
        id: 'preparation',
        name: 'Подготовка',
        type: 'ACTIVE',
        timeCost: 1.0,
        manaCost: 20,
        cooldown: 24.0,
        desc: 'Подбрасывает кинжал вверх и ускоряется на +50% на 2 секунды.',
      },
      {
        id: 'shunpo',
        name: 'Шунпо',
        type: 'ACTIVE',
        timeCost: 0,
        manaCost: 25,
        range: 6,
        damage: 20,
        cooldown: 56.0,
        desc: 'Мгновенный телепорт к цели/кинжалу с нанесением 20 урона. Подбор кинжала снижает КД на 75%.',
      },
      {
        id: 'death-lotus',
        name: 'Цветок смерти',
        type: 'ULTIMATE',
        timeCost: 4.5,
        manaCost: 80,
        range: 5,
        damage: 20,
        cooldown: 64.0,
        desc: 'Шквал кинжалов во всех врагов каждые 0.5с: 20 урона за клинок + Страшные раны (лечение -40%).',
      },
    ],
  },
  {
    id: 'anderson',
    name: 'Александр Андерсон',
    title: 'Паладин Искариот (Hellsing)',
    heroClass: 'STRENGTH',
    faction: 'radiant',
    themeColor: '#713f12',
    accentColor: '#eab308',
    avatarSymbol: 'AA',
    avatarUrl: '/avatars/anderson_avatar.svg',
    stats: {
      level: 1,
      hp: 125,
      maxHp: 125,
      hpRegen: 8,
      mana: 100,
      maxMana: 100,
      manaRegen: 10,
      vision: 10,
      speed: 6,
      armor: 3,
      agility: 4,
      damage: 40,
      period: 4.0,
      critDamage: 80,
      range: 1,
      penetration: 13,
      hit: 4,
    },
    skills: [
      {
        id: 'superhuman',
        name: 'Сверхчеловеческая природа & Крест',
        type: 'PASSIVE',
        timeCost: 0,
        manaCost: 0,
        desc: 'Регенерация 10% макс. HP каждые 4 хода. Блокирует контроль с потерей креста.',
      },
      {
        id: 'bayonet-throw',
        name: 'Противовампирский штык',
        type: 'ACTIVE',
        timeCost: 4.0,
        manaCost: 35,
        range: 10,
        damagePercent: 0.15,
        cooldown: 24.0,
        desc: 'Бросок штыка: 15% текущего HP цели и замедление 40% на 4 секунды.',
      },
      {
        id: 'whirlwind-slash',
        name: 'Круговая атака',
        type: 'ACTIVE',
        timeCost: 4.0,
        manaCost: 40,
        radius: 2,
        damage: 50,
        cooldown: 32.0,
        desc: 'Круговой взмах лезвиями на 2 клетки вокруг: 50 физ. урона всем целям.',
      },
      {
        id: 'barrier-seal',
        name: 'Защитная печать',
        type: 'ACTIVE',
        timeCost: 2.0,
        manaCost: 30,
        range: 10,
        cooldown: 40.0,
        desc: 'Создает непроходимый святой барьер 1x3 клетки на 3 хода.',
      },
      {
        id: 'divine-regen',
        name: 'Божественная регенерация',
        type: 'ULTIMATE',
        timeCost: 2.0,
        manaCost: 90,
        duration: 16.0,
        cooldown: 96.0,
        desc: 'Благословение свыше: +20% HP от недостающего, +10% урона, +15% скорости, регенерация 1.5%/сек.',
      },
    ],
  },
  {
    id: 'gojo',
    name: 'Satoru Gojo',
    title: 'Сильнейший Шаман',
    heroClass: 'INTELLIGENCE',
    faction: 'radiant',
    themeColor: '#0369a1',
    accentColor: '#38bdf8',
    avatarSymbol: 'GJ',
    avatarUrl: '/avatars/gojo_avatar.png',
    stats: {
      level: 1,
      hp: 100,
      maxHp: 100,
      hpRegen: 5,
      mana: 160,
      maxMana: 160,
      manaRegen: 15,
      vision: 12,
      speed: 7,
      armor: 2,
      agility: 4,
      damage: 40,
      period: 4.0,
      critDamage: 80,
      range: 4,
      penetration: 20,
      hit: 50,
    },
    skills: [
      {
        id: 'infinity-shield',
        name: 'Infinity (Бесконечность)',
        type: 'PASSIVE',
        timeCost: 0,
        manaCost: 0,
        desc: 'Пространственный барьер поглощает первые 50 ед. входящего урона за раунд.',
      },
      {
        id: 'lapse-blue',
        name: 'Lapse: Blue (Синий: Притяжение)',
        type: 'ACTIVE',
        timeCost: 2.0,
        manaCost: 40,
        range: 6,
        damage: 45,
        cooldown: 12.0,
        desc: 'Создает вакуум: притягивает цель на 3 клетки к эпицентру и наносит 45 урона.',
      },
      {
        id: 'reversal-red',
        name: 'Reversal: Red (Красный: Отталкивание)',
        type: 'ACTIVE',
        timeCost: 2.0,
        manaCost: 50,
        range: 5,
        damage: 55,
        cooldown: 16.0,
        desc: 'Взрывная волна бесконечности: отталкивает цель на 4 клетки и наносит 55 урона.',
      },
      {
        id: 'hollow-purple',
        name: 'Hollow Purple (Фиолетовый: Аннигиляция)',
        type: 'ACTIVE',
        timeCost: 3.0,
        manaCost: 80,
        range: 12,
        damage: 90,
        cooldown: 32.0,
        desc: 'Мнимая масса летит прямой линией сквозь укрытия на 12 клеток: 90 чистого урона.',
      },
      {
        id: 'unlimited-void',
        name: 'Domain: Unlimited Void',
        type: 'ULTIMATE',
        timeCost: 0,
        manaCost: 120,
        radius: 3,
        duration: 8.0,
        cooldown: 100.0,
        desc: 'Расширение территории 3x3: оглушает всех врагов внутри на 8 секунд.',
      },
    ],
  },
  {
    id: 'sukuna',
    name: 'Ryomen Sukuna',
    title: 'Король Проклятий',
    heroClass: 'STRENGTH',
    faction: 'dire',
    themeColor: '#450a0a',
    accentColor: '#dc2626',
    avatarSymbol: 'SK',
    avatarUrl: '/avatars/sukuna_avatar.png',
    stats: {
      level: 1,
      hp: 120,
      maxHp: 120,
      hpRegen: 5,
      mana: 110,
      maxMana: 110,
      manaRegen: 10,
      vision: 10,
      speed: 6,
      armor: 4,
      agility: 3,
      damage: 45,
      period: 4.0,
      critDamage: 90,
      range: 2,
      penetration: 18,
      hit: 55,
    },
    skills: [
      {
        id: 'king-of-curses',
        name: 'King of Curses (Иммунитет)',
        type: 'PASSIVE',
        timeCost: 0,
        manaCost: 0,
        desc: 'Полный иммунитет к ядам, кровотечениям и гниению. +5 HP и +3 к урону за убийство героя.',
      },
      {
        id: 'dismantle',
        name: 'Dismantle (Рассечение)',
        type: 'ACTIVE',
        timeCost: 1.0,
        manaCost: 35,
        range: 8,
        damage: 40,
        cooldown: 8.0,
        desc: 'Летящий разрез на 8 клеток: 40 урона с повышенным пробитием.',
      },
      {
        id: 'cleave',
        name: 'Cleave (Расщепление)',
        type: 'ACTIVE',
        timeCost: 2.0,
        manaCost: 45,
        range: 2,
        damage: 45,
        cooldown: 12.0,
        desc: 'Ближний разрез: наносит 45 чистого урона, полностью игнорируя броню цели.',
      },
      {
        id: 'furnace-open',
        name: 'Furnace: Open (Пламя Фууга)',
        type: 'ACTIVE',
        timeCost: 3.0,
        manaCost: 70,
        range: 8,
        damage: 65,
        cooldown: 24.0,
        desc: 'Огненная стрела взрывает область 3x3: 65 урона всем целям.',
      },
      {
        id: 'malevolent-shrine',
        name: 'Domain: Malevolent Shrine',
        type: 'ULTIMATE',
        timeCost: 0,
        manaCost: 110,
        radius: 4,
        damage: 35,
        cooldown: 90.0,
        desc: 'Открытая территория радиусом 4: каждый ход наносит 35 урона всем врагам внутри.',
      },
    ],
  },
  {
    id: 'pudge',
    name: 'Pudge',
    title: 'Мясник (Butcher)',
    heroClass: 'STRENGTH',
    faction: 'dire',
    themeColor: '#365314',
    accentColor: '#84cc16',
    avatarSymbol: 'PD',
    avatarUrl: '/avatars/pudge_avatar.png',
    stats: {
      level: 1,
      hp: 160,
      maxHp: 160,
      hpRegen: 8,
      mana: 80,
      maxMana: 80,
      manaRegen: 5,
      vision: 8,
      speed: 5,
      armor: 4,
      agility: 1,
      damage: 45,
      period: 4.0,
      critDamage: 90,
      range: 1,
      penetration: 12,
      hit: 45,
    },
    skills: [
      {
        id: 'meat-hook',
        name: 'Meat Hook',
        type: 'ACTIVE',
        timeCost: 2.0,
        manaCost: 40,
        range: 8,
        damage: 60,
        cooldown: 16.0,
        desc: 'Бросает крюк на 8 клеток: притягивает первую задетую цель к Паджу и наносит 60 урона.',
      },
      {
        id: 'rot',
        name: 'Rot',
        type: 'ACTIVE',
        timeCost: 0,
        manaCost: 0,
        radius: 2,
        damage: 15,
        desc: 'Включаемая аура гниения: наносит 15 урона в секунду Паджу и врагам в радиусе 2, замедляя их.',
      },
      {
        id: 'flesh-heap',
        name: 'Flesh Heap',
        type: 'PASSIVE',
        timeCost: 0,
        manaCost: 0,
        desc: '+10% к сопротивлению магии и +2 к макс. HP за каждое убийство.',
      },
      {
        id: 'dismember',
        name: 'Dismember',
        type: 'ULTIMATE',
        timeCost: 3.0,
        manaCost: 70,
        range: 1,
        damage: 90,
        cooldown: 40.0,
        desc: 'Пожирает врага в ближнем бою: удерживает цель на 3 секунды, нанося 90 урона и исцеляя Паджа.',
      },
    ],
  },
  {
    id: 'invoker',
    name: 'Invoker',
    title: 'Гранд-Маг (Kael)',
    heroClass: 'INTELLIGENCE',
    faction: 'radiant',
    themeColor: '#78350f',
    accentColor: '#fbbf24',
    avatarSymbol: 'IN',
    avatarUrl: '/avatars/invoker_avatar.png',
    stats: {
      level: 1,
      hp: 95,
      maxHp: 95,
      hpRegen: 4,
      mana: 180,
      maxMana: 180,
      manaRegen: 15,
      vision: 10,
      speed: 6,
      armor: 1,
      agility: 2,
      damage: 42,
      period: 4.0,
      critDamage: 84,
      range: 6,
      penetration: 15,
      hit: 50,
    },
    skills: [
      {
        id: 'cold-snap',
        name: 'Cold Snap (QQQ)',
        type: 'ACTIVE',
        timeCost: 1.5,
        manaCost: 40,
        range: 6,
        damage: 25,
        cooldown: 16.0,
        desc: 'Замораживает цель: при каждом ударе враг оглушается на 0.5с и получает доп. урон.',
      },
      {
        id: 'sun-strike',
        name: 'Sun Strike (EEE)',
        type: 'ACTIVE',
        timeCost: 2.0,
        manaCost: 60,
        range: 99,
        damage: 100,
        cooldown: 24.0,
        desc: 'Глобальный луч солнца в любую клетку карты: 100 чистого урона с задержкой 1.7 сек.',
      },
      {
        id: 'chaos-meteor',
        name: 'Chaos Meteor (EEW)',
        type: 'ACTIVE',
        timeCost: 2.5,
        manaCost: 80,
        range: 8,
        damage: 90,
        cooldown: 40.0,
        desc: 'Призывает пылающий метеор, который катится на 6 клеток и сжигает всё на пути.',
      },
    ],
  },
  {
    id: 'rubick',
    name: 'Rubick',
    title: 'Великий Маг (Grand Magus)',
    heroClass: 'INTELLIGENCE',
    faction: 'radiant',
    themeColor: '#064e3b',
    accentColor: '#10b981',
    avatarSymbol: 'RB',
    avatarUrl: '/avatars/rubick_avatar.png',
    stats: {
      level: 1,
      hp: 90,
      maxHp: 90,
      hpRegen: 4,
      mana: 170,
      maxMana: 170,
      manaRegen: 14,
      vision: 10,
      speed: 6,
      armor: 2,
      agility: 3,
      damage: 38,
      period: 4.0,
      critDamage: 76,
      range: 6,
      penetration: 12,
      hit: 48,
    },
    skills: [
      {
        id: 'telekinesis',
        name: 'Telekinesis',
        type: 'ACTIVE',
        timeCost: 1.5,
        manaCost: 35,
        range: 5,
        cooldown: 18.0,
        desc: 'Поднимает цель в воздух на 1.5 сек и швыряет её на расстояние до 3 клеток, оглушая при падении.',
      },
      {
        id: 'fade-bolt',
        name: 'Fade Bolt',
        type: 'ACTIVE',
        timeCost: 1.5,
        manaCost: 40,
        range: 6,
        damage: 45,
        cooldown: 12.0,
        desc: 'Электрический разряд: отскакивает по целям, наносит 45 урона и снижает их урон на 15%.',
      },
      {
        id: 'spell-steal',
        name: 'Spell Steal',
        type: 'ULTIMATE',
        timeCost: 1.0,
        manaCost: 50,
        range: 8,
        cooldown: 20.0,
        desc: 'Ворует последнюю примененную способность вражеского героя.',
      },
    ],
  },
  {
    id: 'sf',
    name: 'Shadow Fiend',
    title: 'Повелитель Душ (Nevermore)',
    heroClass: 'AGILITY',
    faction: 'dire',
    themeColor: '#1c1917',
    accentColor: '#ef4444',
    avatarSymbol: 'SF',
    avatarUrl: '/avatars/sf_avatar.png',
    stats: {
      level: 1,
      hp: 95,
      maxHp: 95,
      hpRegen: 4,
      mana: 120,
      maxMana: 120,
      manaRegen: 8,
      vision: 9,
      speed: 6,
      armor: 2,
      agility: 4,
      damage: 42,
      period: 4.0,
      critDamage: 84,
      range: 5,
      penetration: 15,
      hit: 50,
    },
    skills: [
      {
        id: 'shadowraze-near',
        name: 'Shadowraze (Ближний)',
        type: 'ACTIVE',
        timeCost: 1.0,
        manaCost: 30,
        range: 2,
        damage: 50,
        cooldown: 8.0,
        desc: 'Взрыв темных душ на расстоянии 2 клеток: 50 урона.',
      },
      {
        id: 'shadowraze-medium',
        name: 'Shadowraze (Средний)',
        type: 'ACTIVE',
        timeCost: 1.0,
        manaCost: 30,
        range: 4,
        damage: 50,
        cooldown: 8.0,
        desc: 'Взрыв темных душ на расстоянии 4 клеток: 50 урона.',
      },
      {
        id: 'shadowraze-far',
        name: 'Shadowraze (Дальний)',
        type: 'ACTIVE',
        timeCost: 1.0,
        manaCost: 30,
        range: 6,
        damage: 50,
        cooldown: 8.0,
        desc: 'Взрыв темных душ на расстоянии 6 клеток: 50 урона.',
      },
      {
        id: 'requiem-of-souls',
        name: 'Requiem of Souls',
        type: 'ULTIMATE',
        timeCost: 2.0,
        manaCost: 100,
        radius: 4,
        damage: 120,
        cooldown: 80.0,
        desc: 'Реквием душ: взрыв во все стороны на 4 клетки, наносящий до 120 урона и накладывающий Страх.',
      },
    ],
  },
  {
    id: 'monesy',
    name: 'm0NESY',
    title: 'AWP Prodigy / Снайпер',
    heroClass: 'AGILITY',
    faction: 'radiant',
    themeColor: '#0f172a',
    accentColor: '#38bdf8',
    avatarSymbol: 'M0',
    avatarUrl: '/avatars/monesy_avatar.png',
    stats: {
      level: 1,
      hp: 90,
      maxHp: 90,
      hpRegen: 4,
      mana: 100,
      maxMana: 100,
      manaRegen: 8,
      vision: 12,
      speed: 7,
      armor: 1,
      agility: 5,
      damage: 55,
      period: 4.0,
      critDamage: 110,
      range: 10,
      penetration: 30,
      hit: 60,
    },
    skills: [
      {
        id: 'awp-wallbang',
        name: 'AWP Wallbang',
        type: 'ACTIVE',
        timeCost: 2.5,
        manaCost: 35,
        range: 12,
        damage: 75,
        cooldown: 12.0,
        desc: 'Выстрел из AWP через препятствия и деревья на 12 клеток: 75 физ. урона.',
      },
      {
        id: 'oneway-smoke',
        name: 'One-Way Smoke',
        type: 'ACTIVE',
        timeCost: 1.0,
        manaCost: 25,
        range: 6,
        cooldown: 16.0,
        desc: 'Бросает дымовую гранату: блокирует обзор врагам, оставляя Монеси видимость.',
      },
      {
        id: 'flashbang',
        name: 'Flashbang',
        type: 'ACTIVE',
        timeCost: 1.0,
        manaCost: 20,
        range: 6,
        cooldown: 14.0,
        desc: 'Ослепляет врагов в радиусе 2 клеток: 100% шанс промаха на 1 ход.',
      },
      {
        id: 'clutch-master',
        name: '1v5 Clutch Master',
        type: 'ULTIMATE',
        timeCost: 0,
        manaCost: 80,
        duration: 8.0,
        cooldown: 60.0,
        desc: 'Ульта: скорость +4, крит шанс 100%, уклонение +40% на 8 секунд.',
      },
    ],
  },
  {
    id: 'minos',
    name: 'Minos Prime',
    title: 'Судия Ультракилла (Ultrakill)',
    heroClass: 'STRENGTH',
    faction: 'radiant',
    themeColor: '#172554',
    accentColor: '#60a5fa',
    avatarSymbol: 'MP',
    avatarUrl: '/avatars/minos_avatar.png',
    stats: {
      level: 1,
      hp: 130,
      maxHp: 130,
      hpRegen: 6,
      mana: 100,
      maxMana: 100,
      manaRegen: 8,
      vision: 10,
      speed: 8,
      armor: 3,
      agility: 5,
      damage: 50,
      period: 4.0,
      critDamage: 100,
      range: 2,
      penetration: 20,
      hit: 55,
    },
    skills: [
      {
        id: 'judgement',
        name: 'JUDGEMENT!',
        type: 'ACTIVE',
        timeCost: 2.0,
        manaCost: 35,
        range: 6,
        damage: 60,
        cooldown: 14.0,
        desc: 'Рывок к врагу с разящим дропкиком: 60 урона и взрывная волна вокруг.',
      },
      {
        id: 'thy-end-is-now',
        name: 'THY END IS NOW!',
        type: 'ACTIVE',
        timeCost: 2.5,
        manaCost: 40,
        range: 2,
        damage: 70,
        cooldown: 16.0,
        desc: 'Серия из 4 молниеносных ударов в ближнем бою: суммарно 70 урона.',
      },
      {
        id: 'prepare-thyself',
        name: 'PREPARE THYSELF!',
        type: 'ACTIVE',
        timeCost: 1.5,
        manaCost: 30,
        range: 8,
        damage: 45,
        cooldown: 10.0,
        desc: 'Выпускает сгусток чистой змеевидной энергии на 8 клеток: 45 урона.',
      },
      {
        id: 'crush',
        name: 'CRUSH!',
        type: 'ULTIMATE',
        timeCost: 2.0,
        manaCost: 80,
        range: 6,
        damage: 95,
        cooldown: 50.0,
        desc: 'Удар с небес по площади 3x3: 95 урона и оглушение на 1 ход.',
      },
    ],
  },
  // 13. Schrödinger
  {
    id: 'schrodinger',
    name: 'Шрёдингер',
    title: 'Квантовый наблюдатель / Кот в коробке',
    heroClass: 'INTELLIGENCE',
    faction: 'dire',
    themeColor: '#334155',
    accentColor: '#38bdf8',
    avatarSymbol: 'SC',
    avatarUrl: '/avatars/schrodinger_avatar.svg',
    stats: {
      level: 1,
      hp: 100,
      maxHp: 100,
      hpRegen: 5,
      mana: 100,
      maxMana: 100,
      manaRegen: 10,
      vision: 8,
      speed: 6,
      armor: 1,
      agility: 3,
      damage: 20,
      period: 4.0,
      critDamage: 40,
      range: 1,
      penetration: 15,
      hit: 50,
    },
    skills: [
      {
        id: 'everywhere-nowhere',
        name: 'Everywhere & Nowhere',
        type: 'ACTIVE',
        timeCost: 3.0,
        manaCost: 25,
        range: 99,
        damage: 0,
        cooldown: 24.0,
        desc: 'Шрёдингер перемещается в любую точку карты на 8-32с, затем возвращается в точку телепорта.',
      },
      {
        id: 'prion',
        name: 'Prion',
        type: 'ACTIVE',
        timeCost: 2.0,
        manaCost: 25,
        range: 99,
        damage: 0,
        cooldown: 24.0,
        desc: 'Вселяется в голову любого противника по всей карте, получая его обзор.',
      },
      {
        id: 'dead-alive',
        name: 'Dead & Alive',
        type: 'PASSIVE',
        timeCost: 0,
        manaCost: 0,
        range: 0,
        damage: 0,
        cooldown: 200.0,
        desc: 'Шрёдингер возрождается сразу же после смерти без времени ожидания на возрождение.',
      },
      {
        id: 'mind-control',
        name: 'Mind Control',
        type: 'ACTIVE',
        timeCost: 2.0,
        manaCost: 35,
        range: 6,
        damage: 0,
        cooldown: 32.0,
        desc: 'Сбивает с толку противника: накладывает безмолвие (Silence) на 4-16 секунд.',
      },
      {
        id: 'last-cat-live',
        name: 'Last Cat Live',
        type: 'ULTIMATE',
        timeCost: 0,
        manaCost: 150,
        range: 1,
        damage: 999,
        cooldown: 200.0,
        desc: 'При получении смертельного урона убивает атаковавшего соперника и восстанавливает 30-70% HP.',
      },
    ],
  },
  // 14. Alucard
  {
    id: 'alucard',
    name: 'Алукард',
    title: 'Истинный Вампир / Носферату Хеллсинга',
    heroClass: 'INTELLIGENCE',
    faction: 'radiant',
    themeColor: '#881337',
    accentColor: '#e11d48',
    avatarSymbol: 'AL',
    avatarUrl: '/avatars/alucard_avatar.svg',
    stats: {
      level: 1,
      hp: 115,
      maxHp: 115,
      hpRegen: 8,
      mana: 120,
      maxMana: 120,
      manaRegen: 10,
      vision: 10,
      speed: 6,
      armor: 3,
      agility: 4,
      damage: 40,
      period: 4.0,
      critDamage: 80,
      range: 5,
      penetration: 13,
      hit: 40,
    },
    skills: [
      {
        id: 'army-of-souls',
        name: 'Армия душ',
        type: 'PASSIVE',
        timeCost: 0,
        manaCost: 0,
        range: 8,
        damage: 0,
        cooldown: 0,
        desc: 'Поглощает души погибших в радиусе 8: +2.5 урона и +10 макс HP навсегда за душу.',
      },
      {
        id: 'blood-drain',
        name: 'Вытягивание крови',
        type: 'ACTIVE',
        timeCost: 2.0,
        manaCost: 35,
        range: 6,
        damage: 40,
        cooldown: 28.0,
        desc: 'Наносит 40 маг. урона и исцеляет на 20 HP (+3 за душу). Дает заряд жажды крови.',
      },
      {
        id: 'cromwell-seal-2',
        name: 'Печать Кромвеля 2',
        type: 'ACTIVE',
        timeCost: 2.0,
        manaCost: 0,
        range: 5,
        damage: 25,
        cooldown: 32.0,
        desc: 'Вызывает адских церберов: кусают врагов вокруг. Стоит 8% макс HP.',
      },
      {
        id: 'cromwell-seal-1',
        name: 'Печать Кромвеля 1',
        type: 'ACTIVE',
        timeCost: 4.0,
        manaCost: 0,
        range: 2,
        damage: 20,
        cooldown: 40.0,
        desc: 'Превращается в облако 2x2: неуязвимость, +35% скорости, замедление врагов 40% и вампиризм 50%.',
      },
      {
        id: 'cromwell-seal-0',
        name: 'Печать Кромвеля 0',
        type: 'ULTIMATE',
        timeCost: 1.0,
        manaCost: 0,
        range: 3,
        damage: 0,
        cooldown: 96.0,
        desc: 'Высвобождает накопленные души в виде подконтрольных крипов ближнего боя.',
      },
    ],
  },
  // 15. Gabriel
  {
    id: 'gabriel',
    name: 'Габриэль',
    title: 'Судья Ада / Апостол Небес',
    heroClass: 'AGILITY',
    faction: 'radiant',
    themeColor: '#78350f',
    accentColor: '#f59e0b',
    avatarSymbol: 'GB',
    avatarUrl: '/avatars/gabriel_avatar.svg',
    stats: {
      level: 1,
      hp: 100,
      maxHp: 100,
      hpRegen: 10,
      mana: 100,
      maxMana: 100,
      manaRegen: 10,
      vision: 11,
      speed: 6,
      armor: 5,
      agility: 1,
      damage: 30,
      period: 4.0,
      critDamage: 70,
      range: 10,
      penetration: 15,
      hit: 15,
    },
    skills: [
      {
        id: 'light-speed',
        name: 'Light Speed',
        type: 'ACTIVE',
        timeCost: 0,
        manaCost: 20,
        range: 10,
        damage: 0,
        cooldown: 12.0,
        desc: 'Моментально перемещается в указанную точку на расстояние до 10 клеток.',
      },
      {
        id: 'divine-spear',
        name: 'Divine Spear',
        type: 'ACTIVE',
        timeCost: 2.0,
        manaCost: 30,
        range: 15,
        damage: 60,
        cooldown: 24.0,
        desc: 'Бросает световое копьё: 60 урона, 100% попадание, 20 пробития.',
      },
      {
        id: 'divine-rapier',
        name: 'Divine Rapier',
        type: 'ACTIVE',
        timeCost: 4.0,
        manaCost: 60,
        range: 1,
        damage: 120,
        cooldown: 32.0,
        desc: 'Серия из 4 сокрушительных ударов световой рапирой в упор.',
      },
      {
        id: 'divine-axe',
        name: 'Divine Axe',
        type: 'ACTIVE',
        timeCost: 2.0,
        manaCost: 30,
        range: 15,
        damage: 50,
        cooldown: 24.0,
        desc: 'Выкидывает световой топор с абсолютным пробитием 100.',
      },
      {
        id: 'angel-rage',
        name: 'Angel Rage',
        type: 'PASSIVE',
        timeCost: 0,
        manaCost: 0,
        range: 0,
        damage: 0,
        cooldown: 0,
        desc: 'При HP < 50% ярость: скорость 2x, время применения и атак ускоряются вдвое, перезарядка способностей ускоряется вдвое.',
      },
      {
        id: 'angel-power',
        name: 'Angel Power',
        type: 'ULTIMATE',
        timeCost: 0,
        manaCost: 150,
        range: 1,
        damage: 0,
        cooldown: 160.0,
        desc: 'Стойка парных клинков ближнего боя: урон 2x, скорость 2x, пробитие и попадание до 50 на 24с.',
      },
    ],
  },
];
