/**
 * Tower & Ancient / Throne data specification from Google Docs:
 * All towers are 2x2 cells, immobile, with an attack period of 4.0 seconds.
 */

export const TOWER_STATS = {
  T1: {
    tier: 1,
    name: 'Tower Tier 1',
    hp: 1000,
    maxHp: 1000,
    armor: 50,
    vision: 11,
    damage: 30,
    critDamage: 60,
    range: 10,
    penetration: 20,
    hit: 15,
    attackPeriod: 4.0, // seconds
    size: 2,
    isImmobile: true,
  },
  T2: {
    tier: 2,
    name: 'Tower Tier 2',
    hp: 1500,
    maxHp: 1500,
    armor: 75,
    vision: 11,
    damage: 60,
    critDamage: 120,
    range: 10,
    penetration: 40,
    hit: 30,
    attackPeriod: 4.0,
    size: 2,
    isImmobile: true,
  },
  T3: {
    tier: 3,
    name: 'Tower Tier 3',
    hp: 2000,
    maxHp: 2000,
    armor: 75,
    vision: 11,
    damage: 90,
    critDamage: 180,
    range: 10,
    penetration: 60,
    hit: 45,
    attackPeriod: 4.0,
    size: 2,
    isImmobile: true,
  },
  T4: {
    tier: 4,
    name: 'Tower Tier 4',
    hp: 2500,
    maxHp: 2500,
    armor: 75,
    vision: 11,
    damage: 90,
    critDamage: 180,
    range: 10,
    penetration: 60,
    hit: 45,
    attackPeriod: 4.0,
    size: 2,
    isImmobile: true,
  },
  THRONE: {
    tier: 5,
    name: 'Ancient Throne / World Tree',
    hp: 3000,
    maxHp: 3000,
    armor: 50,
    vision: 12,
    damage: 0,
    range: 0,
    size: 3,
    isImmobile: true,
  },
};
